# Generated by Django 5.2.16 on 2026-07-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="currency",
            field=models.CharField(
                choices=[
                    ("INR", "Indian Rupee (₹)"),
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("AUD", "Australian Dollar (A$)"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
    ]
